homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: -2
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  # Example configuration.yaml entry
  auth_providers:
   - type: homeassistant
   # Uncomment next line if you want to enable legacy API password support
  #  - type: legacy_api_password

# Enable the auth component
auth:
# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  themes:
    dark:
      primary-color: blue
    shiny:
      primary-color: red
    simple:
      primary-color: white
      primary-text-color: blue

cloud:
  !include cloud.yaml

  # Enables configuration UI
config:

http:
  server_port: 8123
  trusted_networks:
    - 192.168.2.0/24
  base_url: home.eavv.nl
api:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

wake_on_lan:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  exclude:
    entities:
    - sensor.washing_machine_alarm_level
    - sensor.washing_machine_alarm_type
    - sensor.washing_machine_current
    - sensor.washing_machine_exporting
    - sensor.washing_machine_interval
    - sensor.washing_machine_interval_2
    - sensor.washing_machine_interval_3
    - sensor.washing_machine_interval_4
    - sensor.washing_machine_energy
    - sensor.washing_machine_power_management
    - sensor.washing_machine_previous_reading
    - sensor.washing_machine_previous_reading_2
    - sensor.washing_machine_previous_reading_3
    - sensor.washing_machine_previous_reading_4
    - sensor.washing_machine_sourcenodeid
    - sensor.washing_machine_voltage
    - sensor.dryer_alarm_level
    - sensor.dryer_alarm_type
    - sensor.dryer_current
    - sensor.dryer_exporting
    - sensor.dryer_interval
    - sensor.dryer_interval_2
    - sensor.dryer_interval_3
    - sensor.dryer_interval_4
    - sensor.dryer_energy
    - sensor.dryer_power_management
    - sensor.dryer_previous_reading
    - sensor.dryer_previous_reading_2
    - sensor.dryer_previous_reading_3
    - sensor.dryer_previous_reading_4
    - sensor.dryer_sourcenodeid
    - sensor.dryer_voltage
    - sensor.bedroom_alarm_level
    - sensor.bedroom_alarm_type
    - sensor.bedroom_exporting
    - sensor.bedroom_power_management
    - sensor.bedroom_previous_reading
    - sensor.bedroom_sourcenodeid


# View all events in a logbook
logbook:
  exclude:
    entities:
    - sensor.washing_machine_alarm_level
    - sensor.washing_machine_alarm_type
    - sensor.washing_machine_current
    - sensor.washing_machine_exporting
    - sensor.washing_machine_interval
    - sensor.washing_machine_interval_2
    - sensor.washing_machine_interval_3
    - sensor.washing_machine_interval_4
    - sensor.washing_machine_energy
    - sensor.washing_machine_power_management
    - sensor.washing_machine_previous_reading
    - sensor.washing_machine_previous_reading_2
    - sensor.washing_machine_previous_reading_3
    - sensor.washing_machine_previous_reading_4
    - sensor.washing_machine_sourcenodeid
    - sensor.washing_machine_voltage
    - sensor.dryer_alarm_level
    - sensor.dryer_alarm_type
    - sensor.dryer_current
    - sensor.dryer_exporting
    - sensor.dryer_interval
    - sensor.dryer_interval_2
    - sensor.dryer_interval_3
    - sensor.dryer_interval_4
    - sensor.dryer_energy
    - sensor.dryer_power_management
    - sensor.dryer_previous_reading
    - sensor.dryer_previous_reading_2
    - sensor.dryer_previous_reading_3
    - sensor.dryer_previous_reading_4
    - sensor.dryer_sourcenodeid
    - sensor.dryer_voltage
    - sensor.bedroom_alarm_level
    - sensor.bedroom_alarm_type
    - sensor.bedroom_exporting
    - sensor.bedroom_power_management
    - sensor.bedroom_previous_reading
    - sensor.bedroom_sourcenodeid
    - sensor.weather_condition
    - sensor.weather_detailed_condition
    - sensor.weather_humidity
    - sensor.weather_precipitation
    - sensor.weather_stationname
    - sensor.weather_symbol
    - sensor.weather_temperature
    - sensor.weather_wind_direction
    - sensor.weather_wind_force
    - weather.br_unknown_station
    - binary_sensor.living_room_motion_sensor
    - sensor.kitchen_motion_sensor
    - sensor.living_light_level
    - sensor.living_room_alarm_level
    - sensor.living_room_alarm_type
    - sensor.living_room_burglar
    - sensor.living_room_luminance
    - sensor.living_room_sourcenodeid
    - sensor.living_room_temperature
    - sensor.kitchen_light_level
    - sensor.kitchen_motion_sensor
    - sensor.people_in_kitchen_mean
    - sensor.people_in_kitchen_ratio
    - sensor.hassuptime
    - sensor.uptime

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

sensor: !include components/sensors.yaml
# sensor 2: !include components/templates.yaml

binary_sensor:
  name: 'people_awake'
  platform: 'bayesian'
  prior: 0.4
  probability_threshold: 0.79999
  observations:
    - entity_id: 'sun.sun'
      prob_given_true: 0.8
      platform: 'state'
      to_state: 'above_horizon'

    - entity_id: 'device_tracker.eduardsiphone_router'
      prob_given_true: 0.8
      platform: 'state'
      to_state: 'not_home'
    - entity_id: 'group.willemijn'
      prob_given_true: 0.8
      platform: 'state'
      to_state: 'not_home'

    - entity_id: 'device_tracker.eduardsiphone_router'
      prob_given_true: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'group.willemijn'
      prob_given_true: 0.8
      platform: 'state'
      to_state: 'home'

    - entity_id: 'media_player.tv'
      prob_given_true: 0.6
      platform: 'state'
      to_state: 'playing'
    - entity_id: 'media_player.bedroom'
      prob_given_true: 0.6
      platform: 'state'
      to_state: 'playing'

    - entity_id: 'binary_sensor.living_room_motion_sensor'
      prob_given_true: 0.55
      platform: 'state'
      to_state: 'on'
    - entity_id: 'sensor.kitchen_motion_sensor'
      prob_given_true: 0.55
      platform: 'state'
      to_state: 'on'

#device trackers
device_tracker:
  - platform: asuswrt
    host: !secret router_ip
    #port: 8443
    protocol: telnet
    username: !secret asus_user
    password: !secret asus_pw
    interval_seconds: 12
    consider_home: 120
    mode: router
    track_new_devices: no
    new_device_defaults:
      hide_if_away: true
    
#components
notify: !include components/notify.yaml
switch: !include components/switch.yaml
media_player: !include components/mediaplayers.yaml
group: !include components/groups.yaml

hue:
  bridges:
    - host: !secret hue_ip

#automation
automation: !include_dir_merge_list automation
script: !include scripts.yaml

#timer
timer: !include components/timer.yaml

# Text to speech
tts:
  - platform: microsoft
    api_key: !secret speech_api_key
    language: en-us
    gender: Female
    type: JessaRUS
    rate: 20
    volume: -50
    pitch: high
    contour: (0, 0) (100, 100)

ios: !include components/ios.yaml

cover:
  - platform: brunt
    username: !secret brunt_username
    password: !secret brunt_password

zone:
  - name: Home
    latitude: !secret lat
    longitude:  !secret long
    radius: 15
    icon: mdi:account-multiple
  - name: Work
    latitude: !secret work_lat
    longitude: !secret work_long
    radius: 150
    icon: mdi:microsoft

zwave:
  usb_path: /dev/ttyACM0
  debug: true

input_boolean:
  tomato_flow:
    name: Tomato Flow
    icon: mdi:food-apple
  resume_music:
    # name: Resume the music when the TV turns off
    icon: mdi:music-note
  alarm_on:
    name: Alarm Active
    icon: mdi:alarm
  washingmachine_busy:
    name: Washing Machine Busy
    initial: off
    icon: mdi:washing-machine
  dryer_busy:
    name: Dryer Busy
    initial: off
    icon: mdi:tumble-dryer
  clear_day:
    name: Clear Day
    icon: mdi:weather-sunny
  cooking:
    name: Cooking
    icon:  mdi:stove
  after_cooking:
    name: After Cooking
    icon: mdi:food-variant
  shower:
    name: Shower
    icon: mdi:shower

input_datetime:
  alarm_clock_time:
    name: Alarm Clock
    has_time: true

input_number:
  microsoft_stock:
    name: Microsoft Stock
    min: 0
    max: 5000
    step: 1
    icon: mdi:microsoft
    mode: box

weather:
  - platform: buienradar
    forecast: True

coinbase:
  api_key: !secret coinbase_key 
  api_secret: !secret coinbase_secret
  exchange_rate_currencies:
    - BTC
    - ETH
    - LTC

homekit:
  filter:
    include_domains:
      - cover
      - light
      - switch
    exclude_entities:
      - light.dlight1
      - light.dlight2
      - light.dlight3
      - light.kitchen      
      - light.lamp_links
      - light.lamp_rechts
      - light.spot_links
      - light.spot_rechts
      - light.tapdimmer
      - switch.neo_coolcam_power_plug_12a_switch
      - switch.neo_coolcam_power_plug_12a_switch_2
      - switch.qubino_zmnhvdx_flush_dimmer_010v_switch
  auto_start: False

sabnzbd:
  host: !secret host_ip
  port: !secret sab_port
  api_key: !secret sab_api_key
  sensors:
    - 'current_status'
    - 'speed'
    - 'queue_size'
    - 'queue_remaining'
    - 'disk_size'
    - 'disk_free'


# azure_event_grid:
#   update_notify:
#     host: !secret eg_host
#     topic key: !secret topic_key
#     monitored_variables: 
#       - event type
#   test:
#     monitored_variables:
#       - topic

# logger:
#   default: error
#   logs:
    # custom_components.sensor.bunq: debug
    # custom_components.media_player.webostv: debug
#     custom_components.media_player.xboxone: debug
#     # homeassistant.components.mqtt: info
#     homeassistant.components.azure_event_grid: debug
#     azure_event_grid: debug
#     custom_components.azure_event_grid: debug
#     custom_components.sensor.azure_event_grid: debug
    # homeassistant.components.media_player.xbox_one: debug
    # custom_components.media_player.xboxone: debug

