title: Home
views: 
# living room
  - icon: mdi:home-assistant
    title: Living Room
    id: living
    cards:
    - type: glance
      title: Status
      entities:
        - sensor.kitchen_light_level
        - sensor.living_room_luminance
        - binary_sensor.front_door_sensor
        - sensor.temperature
        - sensor.living_room_temperature

    - type: vertical-stack
      cards:
      - type: glance
        title: Media
        entities:
          - media_player.multimedia
          - media_player.xbox
          - media_player.tv
          - media_player.plex_plex_sn16y90mhqpsit50ds4iuvc3
          - media_player.bedroom
          - media_player.bathroom
          - media_player.living_room

      - type: media-control
        entity: media_player.multimedia
          
      - type: media-control
        entity: media_player.bedroom

      - type: entities
        title: Media Rules
        entities:
          - automation.movie__pause
          - automation.movie__play
          - automation.tv_off_play_music
          - automation.tv_off_sonos_on
          - automation.tv_on_pause_sonos
          - input_boolean.resume_music
          - automation.play_media
          - automation.play_music

    - type: vertical-stack
      cards:
      - type: entities
        title: Lights
        entities:
          - light.oplaad_lamp
          - light.liggende_lamp
          - light.staande_lamp
          - light.desk_lamp
      - type: entities
        title: Light Rules
        entities:
          - automation.lights_on_at_sunset
          - automation.lights_off_when_away
          - automation.lights_on_when_arriving_home
          - automation.lights_off_after_leaving

    - type: vertical-stack
      cards:
      - type: entities
        title: Blind Controls
        entities:
          - cover.blind
          - sensor.blind_position
          - binary_sensor.people_awake
          - automation.people_awake
          - automation.close_the_blind_when_its_sunny
          - automation.blind_close_at_sunset

      - type: history-graph
        title: Blind
        entities:
          - sensor.blind_position
        hours_to_show: 12
        refresh_interval: 900

      - type: history-graph
        title: Blind - Long
        entities:
          - sensor.blind_position
        hours_to_show: 144
        refresh_interval: 900

      - type: history-graph
        title: Light Levels Short
        entities:
        - sensor.kitchen_light_level
        - sensor.living_room_luminance
        hours_to_show: 3
        refresh_interval: 300

      - type: history-graph
        title: Light Levels Long
        entities:
        - sensor.kitchen_light_level
        - sensor.living_room_luminance
        hours_to_show: 72
        refresh_interval: 300

# rest (laundry, bedroom, bathroom)
  - icon: mdi:hotel
    title: Other Rooms
    id: other
    cards:
    - type: glance
      title: Status
      entities:
        - light.bedroom_level
        - light.fan_level
        - sensor.bathroom_relative_humidity
        - sensor.bathroom_humidity_stats_mean
        - sensor.bathroom_temperature

    - type: glance
      title: Fan
      entities:
        - input_boolean.washingmachine_busy
        - input_boolean.dryer_busy
        - input_boolean.cooking
        - input_boolean.shower

    - type: vertical-stack
      cards:
      - type: entities
        title: Laundry
        entities:
          - automation.washing_machine__ready
          - automation.washing_machine__busy
          - automation.washing_machine__notification
          - automation.dryer__ready
          - automation.dryer__busy
          - automation.dryer__notification

      - type: history-graph
        title: Washing Machine Power
        entities:
          - sensor.washing_machine_power
        hours_to_show: 3
        refresh_interval: 30

      - type: history-graph
        title: Dryer Power
        entities:
          - sensor.dryer_power
        hours_to_show: 3
        refresh_interval: 30

    - type: entities
      title: Bedroom
      entities:
        - light.bedroom_level
        - automation.alarm_automation
        - input_boolean.alarm_on
        - input_datetime.alarm_clock_time

    - type: entities
      title: Front Door
      entities:
        - binary_sensor.front_door_sensor
        - automation.notify_when_door_is_open
        - automation.notify_when_door_stays_open

    - type: history-graph
      title: Bathroom Humidity
      entities:
        - sensor.bathroom_relative_humidity
        - sensor.bathroom_humidity_stats_mean
      hours_to_show: 24
      refresh_interval: 10

# people
  - icon: mdi:human-male-female
    title: People
    id: people
    cards:
    - type: glance
      title: People
      entities:
        - group.willemijn
        - group.eduard
        - sensor.eduards_iphone_battery_level
        - sensor.eduards_iphone_battery_state
        - sensor.kitchen_motion_sensor
        - sensor.people_in_kitchen_mean
        - sensor.people_in_kitchen_ratio

    - type: map
      aspect_ratio: 50%
      entities:
        - entity: device_tracker.eduards_iphone
        - zone.home
        - zone.work

    - type: entities
      title: People Automations
      entities:
        - automation.eduard_arrives_home
        - automation.eduard_leaves_home
        - automation.willemijn_arrives_home
        - automation.willemijn_leaves_home
        - automation.lights_on_when_arriving_home
        - automation.lights_off__ios

    - type: entities
      title: Tomato Timer
      entities:
        - timer.tomato
        - input_boolean.tomato_flow
        - automation.start_tomato_flow
        - automation.stop_tomato_flow
        - automation.tomato_timer_finished__break
        - automation.tomato_timer_finished__resume

    - type: history-graph
      title: People In Kitchen
      entities:
        - sensor.people_in_kitchen_mean
        - sensor.people_in_kitchen_ratio
      hours_to_show: 24
      refresh_interval: 300

# finance & weather
  - icon: mdi:weather-partlycloudy
    title: Weather
    id: weather
    cards:
    - type: vertical-stack
      cards:
      - type: glance
        title: Status
        entities:
          - sensor.clear_day
          - sensor.weather_temperature
          - sensor.temperature
          - sensor.living_room_temperature
          - sensor.sun_elevation
          - sensor.sun_azimuth
      - type: history-graph
        title: Temperatures
        entities:
          - sensor.temperature
          - sensor.weather_temperature
          - sensor.living_room_temperature
        hours_to_show: 12
        refresh_interval: 60
      - type: history-graph
        title: Temperatures - Long
        entities:
          - sensor.temperature
          - sensor.weather_temperature
          - sensor.living_room_temperature
        hours_to_show: 336
        refresh_interval: 900

      - type: history-graph
        title: Sun
        entities:
          - sensor.sun_elevation
          - sensor.sun_azimuth
        hours_to_show: 72
        refresh_interval: 300

    - type: vertical-stack
      cards:
      - type: entities
        title: Weather
        entities:
          - sun.sun
          - sensor.weather_symbol
          - sensor.weather_condition
          - sensor.weather_detailed_condition
          - sensor.weather_temperature
          - sensor.weather_precipitation
          - sensor.weather_humidity
          - sensor.weather_wind_direction
          - sensor.weather_wind_force
          - sensor.weather_stationname

      - type: weather-forecast
        entity: weather.br_unknown_station

  - icon: mdi:currency-eur
    title: External Info
    id: external
    cards:
    - type: vertical-stack
      cards: 
      - type: entities
        title: Stock
        entities:
          - sensor.microsoft
          - input_number.microsoft_stock
          - sensor.microsoft_stock

      - type: history-graph
        title: Microsoft Stock Value
        entities:
          - sensor.microsoft_stock
        hours_to_show: 336
        refresh_interval: 300

    # - type: vertical-stack
    #   cards: 
    #   - type: entities
    #     title: Coinbase
    #     entities:
    #       - sensor.coinbase_total
    #       - sensor.coinbase_btc
    #       - sensor.coinbase_eth
    #       - sensor.coinbase_ltc

    #   - type: history-graph
    #     title: Coinbase Value
    #     entities:
    #       - sensor.coinbase_total
    #     hours_to_show: 336
    #     refresh_interval: 300

    - type: vertical-stack
      cards: 
      - type: entities
        title: Bunq
        entities:
          - sensor.bunq_total
          - sensor.bunq_default
          - sensor.bunq_boodschappen
          - sensor.bunq_uit_eten
          - sensor.bunq_monthly
          - sensor.bunq_we
          - sensor.bunq_evi_van_lanschot
          - sensor.bunq_visa
          - sensor.bunq_amex

      - type: history-graph
        title: Bunq
        entities:
          - sensor.bunq_total
          - sensor.bunq_default
          - sensor.bunq_boodschappen
          - sensor.bunq_uit_eten
          - sensor.bunq_monthly
          - sensor.bunq_we
          - sensor.bunq_evi_van_lanschot
          - sensor.bunq_visa
          - sensor.bunq_amex
        hours_to_show: 24
        refresh_interval: 120

    - type: glance
      title: Misc
      entities:
        - sensor.total_packages
        - sensor.postnl
        - sensor.ups

# server  
  - icon: mdi:server-security
    title: Server
    id: server
    cards:
    - type: vertical-stack
      cards:
      - type: glance
        title: Home Assistant Status
        entities:
          - sensor.hassuptime
          - sensor.current_version
          - sensor.pypi_hass_version
          - sensor.last_boot

      - type: entities
        title: System
        entities:
          - script.reload_ha
          - script.restart_ha
          - automation.notify_me_when_update_is_available
          - automation.startup_notification

    - type: glance
      title: Technical Status
      entities:          
        - sensor.cpu_speed
        - sensor.memory_use_percent
        - sensor.disk_use_percent_
        - sensor.speedtest_download
        - sensor.speedtest_upload
        - sensor.speedtest_ping
        - sensor.myip

    - type: glance
      title: Media tracking
      entities:
        - sensor.sonarr_series
        - sensor.sonarr_upcoming
        - sensor.sonarr_wanted
        - sensor.sonarr_queue
        - sensor.sonarr_commands 
        # - sensor.sonarr_diskspace
        - sensor.sabnzbd_status
        - sensor.sabnzbd_speed
        - sensor.sabnzbd_queue
        - sensor.sabnzbd_left
        - sensor.sabnzbd_disk
        - sensor.sabnzbd_disk_free

    - type: history-graph
      title: Speeds
      entities:
        - entity: sensor.speedtest_download
          name: 'Down'
        - entity: sensor.speedtest_upload
          name: 'Up'
      hours_to_show: 168
      refresh_interval: 300
