title: Home
views:
  - icon: mdi:home-assistant
    title: Home
    cards:
      - type: vertical-stack
        cards:
        - type: glance
          title: People
          entities:
            - group.willemijn
            - sensor.kitchen_motion_sensor
            # - group.eduard
            # - sensor.eduards_iphone_battery_level
            # - sensor.eduards_iphone_battery_state
            # - sensor.eduard_naar_huis

        - type: picture-glance
          image:
          camera_image: 'camera.eduard'
          title: Eduard
          entities:
            - group.eduard
            - sensor.eduards_iphone_battery_level
            - sensor.eduards_iphone_battery_state
            - sensor.eduard_naar_huis
            - sensor.huis_naar_werk
            - sensor.werk_naar_huis

        - type: entities
          title: Finance
          entities:
            - sensor.microsoft
            - sensor.google
            - sensor.apple
            - sensor.amazon
            - sensor.coinbase_total
            - sensor.coinbase_btc
            - sensor.coinbase_eth
            - sensor.coinbase_ltc

        # - type: camera-preview
        #   entity: camera.eduard
      - type: vertical-stack
        cards:
        - type: glance
          title: Home
          entities:
            - sensor.blind_position
            - sensor.temperature
            - sensor.light_level
            - sensor.blind_status
            - binary_sensor.neo_coolcam_doorwindow_detector_sensor
            - cover.blind
            - light.qubino_zmnhvdx_flush_dimmer_010v_level

        - type: entities
          title: Misc
          entities:
            - timer.tomato
            - sensor.total_packages

      - type: vertical-stack
        cards:
        - type: entities
          title: Weather
          entities:
            - sun.sun
            - sensor.weather_symbol
            - sensor.weather_condition
            - sensor.weather_detailed_condition
            - sensor.weather_condition_code_1d
            - sensor.weather_temperature
            - sensor.weather_precipitation
            - sensor.weather_precipitation_forecast_average
            - sensor.weather_humidity
            - sensor.weather_wind_direction
            - sensor.weather_wind_force
            - sensor.weather_stationname

        - type: weather-forecast
          entity: weather.br_unknown_station

      - type: glance
        # Title of the entities card
        title: Media
        # The entities here will be shown in the same order as specified.
        entities:
          - media_player.bedroom
          - media_player.bathroom
          - media_player.living_room
          - media_player.multimedia
          - media_player.tv
          - sensor.plex
          - switch.xbox_one

  - icon: mdi:play-pause
    title: Media
    cards:
      - type: entities
        # Title of the entities card
        title: Media
        # The entities here will be shown in the same order as specified.
        entities:
          - media_player.bedroom
          - media_player.bathroom
          - media_player.living_room
          - media_player.multimedia
          - media_player.tv
          - sensor.plex
          - switch.xbox_one

      - type: entities
        title: Media tracking
        entities:
          - sensor.sonarr_series
          - sensor.sonarr_upcoming
          - sensor.sonarr_wanted
          - sensor.sonarr_queue
          - sensor.sonarr_commands 
          - sensor.sonarr_diskspace
          - sensor.sabnzbd_status
          - sensor.sabnzbd_speed
          - sensor.sabnzbd_queue
          - sensor.sabnzbd_left
          - sensor.sabnzbd_disk
          - sensor.sabnzbd_disk_free

  - icon: mdi:lightbulb-on
    title: Lights
    cards:
      - type: entities
        title: Lights
        entities:
          - light.oplaad_lamp
          - light.liggende_lamp
          - light.staande_lamp
          - light.desk_lamp
      
      - type: entities
        title: Bedroom
        entities:
          - light.aeotec_zw111_nano_dimmer_level_2

  - icon: mdi:chart-line
    title: History
    cards:
      - type: history-graph
        title: Traveltimes
        entities:
          - sensor.huis_naar_werk
          - sensor.werk_naar_huis
        hours_to_show: 192
        refresh: 3600

      - type: history-graph
        title: Temperatures
        entities:
          - sensor.temperature
          - sensor.weather_temperature
        hours_to_show: 72
        refresh: 300

      - type: history-graph
        title: Sun
        entities:
          - sensor.sun_elevation
          - sensor.sun_azimuth
        hours_to_show: 72
        refresh: 300

      - type: history-graph
        title: Blind
        entities:
          - sensor.blind_position
        hours_to_show: 72
        refresh: 900

  - icon: mdi:server
    title: Server
    cards:
      - type: vertical-stack
        cards:
        - type: entities
          title: Technical Status
          entities:          
            - sensor.cpu_speed
            - sensor.cpu_used
            - sensor.ram_used
            - sensor.disk_free_content
            - sensor.disk_used_
            - sensor.received
            - sensor.sent
            - sensor.speedtest_download
            - sensor.speedtest_upload
            - sensor.speedtest_ping
            - sensor.myipopendnscom
            - sensor.last_boot

        - type: entities
          title: System
          entities:
            - sensor.hassuptime
            - automation.startup_notification
            - script.reload_ha
            - script.restart_ha
            - automation.notify_me_when_update_is_available
            - sensor.current_version
            - sensor.pypi_hass_version

      - type: entities
        title: Light Automations
        entities:
          - automation.away_lights_off
          - automation.away_lights_on
          - automation.lights_on_at_sunset
          - automation.lights_off_after_leaving
          - automation.lights_off_when_away

      - type: entities
        title: Media Automations
        entities:
          - automation.movie__pause
          - automation.movie__play
          - automation.tv_off_play_music
          - automation.tv_off_sonos_on
          - automation.tv_on_pause_sonos
          - input_boolean.resume_music
          - automation.play_media
          - automation.play_music

      - type: entities
        title: Tomato Automations
        entities:
          - timer.tomato
          - input_boolean.tomato_flow
          - automation.start_tomato_flow
          - automation.stop_tomato_flow
          - automation.tomato_timer_finished__break
          - automation.tomato_timer_finished__resume

      - type: entities
        title: Blind Automations
        entities:
          - cover.blind
          - sensor.blind_status
          - sensor.blind_position
          - automation.blind_close_at_sunset
          - automation.blind_open_at_sunrise_week
          - automation.blind_open_at_sunrise_weekend
          - automation.close_the_blind_when_its_sunny

      - type: entities
        title: People Automations
        entities:
          - automation.eduard_arrives_home
          - automation.willemijn_arrives_home
          - automation.willemijn_leaves_home
          - automation.lights_on_when_arriving_home
          - automation.lights_off__ios

      - type: entities
        title: Alarm Automations
        entities:
          - automation.alarm_automation
          - input_boolean.alarm_on
          - input_datetime.alarm_clock_time

      - type: entities
        title: Fan Automations
        entities:
          - light.qubino_zmnhvdx_flush_dimmer_010v_level
          - script.fan_full
          - script.fan_background
          - script.fan_off
          - automation.fan_evening
          - automation.fan_morning
