- alias: ios_turn_lights_off
  id: ios_turn_lights_off
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: LIGHTS_TURN_OFF
  action:
  - alias: Turn all lights off
    service: homeassistant.turn_off
    entity_id: group.all_lights

- alias: ios_sonos_turn_on
  id: ios_sonos_turn_on
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SONOS_TURN_ON
  action:
  - alias: Resume music
    service: media_player.media_play
    entity_id: media_player.bedroom